In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(r'/content/ipl.csv')

In [ ]:

df.head(5)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
df.loc[2][['Player Name','Team']]

Player Name    Virat Kohli
Team                   RCB
Name: 2, dtype: object

In [ ]:
df.loc[8][['Player Name','Team']]

Player Name    K L Rahul
Team                  DC
Name: 8, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [ ]:
print("Total Players:", len(df))

Total Players: 156

In [ ]:
top_player = df.loc[df["Runs"].idxmax()]
top_player

Player Name    Sai Sudharsan
Team                      GT
Runs                     759
Matches                   15
Inn                       15
No                         1
HS                      108*
AVG                    54.21
BF                       486
SR                    156.17
100s                       1
50s                        6
4s                        88
6s                        21
Name: 0, dtype: object

In [ ]:
top_player = df.loc[df["Runs"].idxmin()]
top_player

Player Name    Varun Chakaravarthy
Team                           KKR
Runs                             1
Matches                         13
Inn                              1
No                               1
HS                              1*
AVG                              -
BF                               1
SR                           100.0
100s                             0
50s                              0
4s                               0
6s                               0
Name: 148, dtype: object

In [ ]:
np.average =  df.Runs
np.average

0      759
1      717
2      657
3      650
4      627
      ...
151      1
152      1
153      1
154      1
155      1
Name: Runs, Length: 156, dtype: int64

In [ ]:
top5runs  = df.head(5)
top5runs

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
top_player = df.loc[df["SR"].idxmax()]
top_player

Player Name    Kwena Maphaka
Team                      RR
Runs                       8
Matches                    2
Inn                        1
No                         1
HS                        8*
AVG                        -
BF                         2
SR                     400.0
100s                       0
50s                        0
4s                         2
6s                         0
Name: 124, dtype: object

In [ ]:
total_run = df.loc[df["Runs"].idxmax()][['Team','Runs']]
total_run

Team     GT
Runs    759
Name: 0, dtype: object

In [ ]:
score = df[df["Runs"] > 500]
score

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40

In [ ]:
score = df[df["6s"] > 25]
score

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
17,Riyan Parag,RR,393,14,14,2,95,32.75,236,166.52,0,1,27,27

In [ ]:
score = df[df["6s"] > 18].head(5)
score

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
four = df[df["4s"] > 40]
four

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17
20,Travis Head,SRH,374,13,12,0,76,31.17,230,162.60,0,3,50,15

In [ ]:
four = df.loc[df["4s"].idxmax()],['Players Name']
four

(Player Name    Sai Sudharsan
 Team                      GT
 Runs                     759
 Matches                   15
 Inn                       15
 No                         1
 HS                      108*
 AVG                    54.21
 BF                       486
 SR                    156.17
 100s                       1
 50s                        6
 4s                        88
 6s                        21
 Name: 0, dtype: object,
 ['Players Name'])

In [ ]:
six = df.loc[df["6s"].idxmax()],['Players Name']
six

(Player Name    Nicholas Pooran
 Team                       LSG
 Runs                       524
 Matches                     14
 Inn                         14
 No                           2
 HS                         87*
 AVG                      43.67
 BF                         267
 SR                      196.25
 100s                         0
 50s                          5
 4s                          45
 6s                          40
 Name: 10, dtype: object,
 ['Players Name'])

In [ ]:
player_perteam = df["Team"].value_counts()
player_perteam

Team
CSK     19
RR      17
DC      17
MI      16
KKR     15
LSG     15
PBKS    15
GT      14
RCB     14
SRH     14
Name: count, dtype: int64

In [ ]:
avg_sr = df.groupby("Team")["SR"].mean()
avg_sr

Team
CSK     130.346842
DC      119.012941
GT      142.952857
KKR     123.555333
LSG     140.846667
MI      137.221250
PBKS    144.912667
RCB     141.392857
RR      137.220000
SRH     129.773571
Name: SR, dtype: float64

In [ ]:
df["Total_boundaries"] = df["4s"] + df['6s']
df["Total_boundaries"]

0      109
1      107
2       85
3       86
4       93
      ...
151      0
152      0
153      0
154      0
155      0
Name: Total_boundaries, Length: 156, dtype: int64

In [ ]:
df

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,109
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,107
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,85
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,86
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0,0

In [ ]:
Total_boundaries = df.loc[df["Total_boundaries"].idxmax()]
Total_boundaries

Player Name         Sai Sudharsan
Team                           GT
Runs                          759
Matches                        15
Inn                            15
No                              1
HS                           108*
AVG                         54.21
BF                            486
SR                         156.17
100s                            1
50s                             6
4s                             88
6s                             21
Total_boundaries              109
Name: 0, dtype: object

In [ ]:
Total_boundaries = df.loc[df["Total_boundaries"].idxmax()]
Total_boundaries

Player Name    Sai Sudharsan
Team                      GT
Runs                     759
Matches                   15
Inn                       15
Name: 0, dtype: object

In [95]:
top5_boundaries = df.sort_values(by="Total_boundaries", ascending=False).head(5)
top5_boundaries

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,109
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,107
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,93
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28,88
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30,86

In [96]:
top5_boundaries = df.sort_values(by="Runs", ascending=False).head(5)
top5_boundaries

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,109
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,107
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,85
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,86
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,93

In [97]:
top5_boundaries = df.sort_values(by="SR", ascending=False).head(5)
top5_boundaries

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0,1
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0,2
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1,1
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7,12
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1,2

In [102]:
century_players = df[df["100s"] > 0]
century_players

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,109
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,93
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21,73
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25,67
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25,80
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28,74
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15,48
36,Rishabh Pant,LSG,269,14,13,2,118*,24.45,202,133.16,1,1,23,16,39
39,Vaibhav Suryavanshi,RR,252,7,7,0,101,36.00,122,206.55,1,1,18,24,42

In [104]:
century_players = df[df["50s"] > 0].head(5)
century_players

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,109
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,107
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,85
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,86
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,93

In [107]:
low_score = df[(df["Matches"] < 5) & (df["Runs"] < 300)]
low_score

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Total_boundaries
77,Mayank Agarwal,RCB,95,4,4,1,41*,31.67,64,148.43,0,0,10,2,12
78,Manish Pandey,KKR,92,3,3,1,37,46.00,65,141.53,0,0,5,5,10
80,Jonny Bairstow,MI,85,2,2,0,47,42.50,46,184.78,0,0,7,5,12
85,Urvil Patel,CSK,68,3,3,0,37,22.67,32,212.50,0,0,5,6,11
86,Jacob Bethell,RCB,67,2,2,0,55,33.50,39,171.79,0,1,9,3,12
94,Corbin Bosch,MI,47,2,2,0,27,23.50,32,146.87,0,0,3,3,6
102,Sediqullah Atal,DC,22,1,1,0,22,22.00,16,137.50,0,0,0,2,2
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2,3
108,Gerald Coetzee,GT,17,4,2,0,12,8.50,11,154.54,0,0,2,1,3
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1,2
111,Matthew Breetzke,LSG,14,1,1,0,14,14.00,12,116.66,0,0,1,1,2
113,Atharva Taide,SRH,13,1,1,0,13,13.00,9,144.44,0,0,3,0,3
116,Xavier Bartlett,PBKS,11,4,1,0,11,11.00,15,73.33,0,0,1,0,1
120,Kagiso Rabada,GT,9,4,2,1,7*,9.00,8,112.50,0,0,0,1,1
121,Shahbaz Ahmed,LSG,9,3,1,0,9,9.00,8,112.50,0,0,1,0,1
122,Wiaan Mulder,SRH,9,1,1,0,9,9.00,11,81.81,0,0,1,0,1
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0,2
125,Raj Angad Bawa,MI,8,3,1,1,8*,-,4,200.00,0,0,0,0,0
132,Robin Minz,MI,6,2,2,0,3,3.00,15,40.00,0,0,0,0,0
133,Rovman Powell,KKR,5,2,1,0,5,5.00,5,100.00,0,0,1,0,1
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0,1
139,Akash Madhwal,RR,4,4,1,1,4*,-,9,44.44,0,0,0,0,0
140,Madhav Tiwari,DC,3,1,1,0,3,3.00,4,75.00,0,0,0,0,0
142,Kumar Kartikeya Singh,RR,3,4,2,0,2,1.50,5,60.00,0,0,0,0,0
143,Simarjeet Singh,SRH,3,4,3,1,3*,1.50,7,42.85,0,0,0,0,0
146,Spencer Johnson,KKR,2,4,2,2,1*,-,4,50.00,0,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0,0